query category (
    $id: ID 
) {
  category (id: $id) {
    ...categoryFieldsFragment
    categoryProductMaxPrice
    count
    children {
      ...categoryFieldsFragment
    }
    breadcrumbs {
      ...breadcrumbsFragment
    }
    filterableAttributes {
      id
      code
      adminName
      options {
        id
        adminName
      }
    }
  }
}